os: 
  - linux
language:
  - ruby

services: 
  - docker

before_install:
  - docker build -t joethong/docker-react -f Dockerfile.dev . 

script: 
  - docker run -e CI=true joethong/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "docker-react"
  env: "DockerReact-env"
  access_key_id: 
    secure: "$AWS_ACCESSKEY"
  secret_access_key:
    secure: "$AWS_SECRETKEY"
  bucket_path: "docker-react"
  bucket: "elasticbeanstalk-ap-northeast-1-559425326450"