os: 
  - linux
language:
  - ruby

services: 
  - docker

before_install:
  - docker build -t joethong/docker-react -f Dockerfile.dev . 

script: 
  - docker run -e CI=true joethong/docker-react npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "cn-north-1"
  app: "docker-react-test"
  env: "DockerReactTest-env"
  access_key_id: $AWS_ACCESSKEY
  secret_access_key: $AWS_SECRETKEY
  bucket_path: "docker-react"
  bucket: "docker-react"
  on:
      branch: master